# Generated by Django 5.0.3 on 2024-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(default=None, upload_to='D:\\!Local_Repos\\Python\\Netology\\HW\\!DJANGO\\ORM_rework\\static')),
                ('release_date', models.DateField(default=None)),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
